[workspace]
members = [
    "common",
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["John Bolton"]
description = "My solutions for Advent of Code 2023 implemented in Rust."