[package]
name = "day22"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
common = { path = "../common" }
regex = "1.11.1"

[features]
part2 = []
