[package]
name = "day25"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
common = { path = "../common" }
debug_print = "1.0.0"

[features]
part2 = []
