[package]
name = "day15"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
common = { path = "../common" }
regex = "1"

[features]
part2 = []
